//===------------------ DLangDemangleTest.cpp -----------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "llvm/Demangle/Demangle.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"

#include <cstdlib>
#include <utility>

struct DLangDemangleTestFixture
    : public testing::TestWithParam<std::pair<const char *, const char *>> {
  char *Demangled;

  void SetUp() override { Demangled = llvm::dlangDemangle(GetParam().first); }

  void TearDown() override { std::free(Demangled); }
};

TEST_P(DLangDemangleTestFixture, DLangDemangleTest) {
  EXPECT_STREQ(Demangled, GetParam().second);
}

INSTANTIATE_TEST_SUITE_P(
    DLangDemangleTest, DLangDemangleTestFixture,
    testing::Values(
        std::make_pair("_Dmain", "D main"), std::make_pair(nullptr, nullptr),
        std::make_pair("_Z", nullptr), std::make_pair("_DDD", nullptr),
        std::make_pair("_D88", nullptr),
        std::make_pair("_D8demangleZ", "demangle"),
        std::make_pair("_D8demangle4testZ", "demangle.test"),
        std::make_pair("_D8demangle4test5test2Z", "demangle.test.test2"),
        std::make_pair("_D8demangle9anonymous0Z", "demangle.anonymous"),
        std::make_pair("_D8demangle9anonymous03fooZ", "demangle.anonymous.foo"),
        std::make_pair("_D8demangle4test6__initZ",
                       "initializer for demangle.test"),
        std::make_pair("_D8demangle4test6__vtblZ", "vtable for demangle.test"),
        std::make_pair("_D8demangle4test7__ClassZ",
                       "ClassInfo for demangle.test"),
        std::make_pair("_D8demangle4test11__InterfaceZ",
                       "Interface for demangle.test"),
        std::make_pair("_D8demangle4test12__ModuleInfoZ",
                       "ModuleInfo for demangle.test"),
        std::make_pair("_D8demangle4test6__ctorMFZv", "demangle.test.this()"),
        std::make_pair("_D8demangle4test6__dtorMFZv", "demangle.test.~this()"),
        std::make_pair("_D8demangle4test10__postblitMFZv",
                       "demangle.test.this(this)"),
        std::make_pair("_D8demangle4__S14testZ", "demangle.test"),
        std::make_pair("_D8demangle4__Sd4testZ", "demangle.__Sd.test"),
        std::make_pair("_D8demangle1ii", "demangle.i"),
        std::make_pair("_D8demangle2siOi", "demangle.si"),
        std::make_pair("_D8demangle1re", "demangle.r"),
        std::make_pair("_D8demangle1iinvalidtypeseq", nullptr),
        std::make_pair("_D8demangle3ABCQeQg1ai", "demangle.ABC.ABC.ABC.a"),
        std::make_pair("_D8demangle3ABCQeQaaaa1ai", nullptr),
        std::make_pair("_D8demangle4ABCiQfQh1aQh", "demangle.ABCi.ABCi.ABCi.a"),
        std::make_pair("_D8demangle4ABCiQfQh1aQaaa", nullptr),
        std::make_pair("_D8demangle4testPFLAiYi", "demangle.test"),
        std::make_pair("_D8demangle4testFaZv", "demangle.test(char)"),
        std::make_pair("_D8demangle4testFbZv", "demangle.test(bool)"),
        std::make_pair("_D8demangle4testFcZv", "demangle.test(creal)"),
        std::make_pair("_D8demangle4testFdZv", "demangle.test(double)"),
        std::make_pair("_D8demangle4testFeZv", "demangle.test(real)"),
        std::make_pair("_D8demangle4testFfZv", "demangle.test(float)"),
        std::make_pair("_D8demangle4testFgZv", "demangle.test(byte)"),
        std::make_pair("_D8demangle4testFhZv", "demangle.test(ubyte)"),
        std::make_pair("_D8demangle4testFiZv", "demangle.test(int)"),
        std::make_pair("_D8demangle4testFjZv", "demangle.test(ireal)"),
        std::make_pair("_D8demangle4testFkZv", "demangle.test(uint)"),
        std::make_pair("_D8demangle4testFlZv", "demangle.test(long)"),
        std::make_pair("_D8demangle4testFmZv", "demangle.test(ulong)"),
        std::make_pair("_D8demangle4testFZv", "demangle.test()"),
        std::make_pair("_D8demangle4testMFZ2fnMFZv", "demangle.test().fn()"),
        std::make_pair("_D8demangle4testFnZv", "demangle.test(typeof(null))"),
        std::make_pair("_D8demangle4testFNnZv", "demangle.test(typeof(*null))"),
        std::make_pair("_D8demangle4testFoZv", "demangle.test(ifloat)"),
        std::make_pair("_D8demangle4testFpZv", "demangle.test(idouble)"),
        std::make_pair("_D8demangle4testFqZv", "demangle.test(cfloat)"),
        std::make_pair("_D8demangle4testFrZv", "demangle.test(cdouble)"),
        std::make_pair("_D8demangle4testFsZv", "demangle.test(short)"),
        std::make_pair("_D8demangle4testFtZv", "demangle.test(ushort)"),
        std::make_pair("_D8demangle4testFuZv", "demangle.test(wchar)"),
        std::make_pair("_D8demangle4testFvZv", "demangle.test(void)"),
        std::make_pair("_D8demangle4testFwZv", "demangle.test(dchar)"),
        std::make_pair("_D8demangle4testFziZv", "demangle.test(cent)"),
        std::make_pair("_D8demangle4testFzkZv", "demangle.test(ucent)"),
        std::make_pair("_D8demangle4testFOaZv", "demangle.test(shared(char))"),
        std::make_pair("_D8demangle4testFxaZv", "demangle.test(const(char))"),
        std::make_pair("_D8demangle4testFyaZv",
                       "demangle.test(immutable(char))"),
        std::make_pair("_D8demangle4testFNgaZv", "demangle.test(inout(char))"),
        std::make_pair("_D8demangle4testFOxaZv",
                       "demangle.test(shared(const(char)))"),
        std::make_pair("_D8demangle4testFONgaZv",
                       "demangle.test(shared(inout(char)))"),
        std::make_pair("_D8demangle4testFAaZv", "demangle.test(char[])"),
        std::make_pair("_D8demangle4testFAAaZv", "demangle.test(char[][])"),
        std::make_pair("_D8demangle4testFAAAaZv", "demangle.test(char[][][])"),
        std::make_pair("_D8demangle4testFHaaZv", "demangle.test(char[char])"),
        std::make_pair("_D8demangle4testFHHaaaZv",
                       "demangle.test(char[char[char]])"),
        std::make_pair("_D8demangle4testFPaZv", "demangle.test(char*)"),
        std::make_pair("_D8demangle4testFPPaZv", "demangle.test(char**)"),
        std::make_pair("_D8demangle4testFPPPaZv", "demangle.test(char***)"),
        std::make_pair("_D8demangle4testFG42aZv", "demangle.test(char[42])"),
        std::make_pair("_D8demangle4testFG42G42aZv",
                       "demangle.test(char[42][42])"),
        std::make_pair("_D8demangle4testFG42G42G42aZv",
                       "demangle.test(char[42][42][42])"),
        std::make_pair("_D8demangle4testFG1234567890aZv",
                       "demangle.test(char[1234567890])"),
        std::make_pair("_D8demangle4testFNhG8gZv",
                       "demangle.test(__vector(byte[8]))"),
        std::make_pair("_D8demangle4testFNhG16gZv",
                       "demangle.test(__vector(byte[16]))"),
        std::make_pair("_D8demangle4testFNhG32gZv",
                       "demangle.test(__vector(byte[32]))"),
        std::make_pair("_D8demangle4testFNhG4sZv",
                       "demangle.test(__vector(short[4]))"),
        std::make_pair("_D8demangle4testFNhG8sZv",
                       "demangle.test(__vector(short[8]))"),
        std::make_pair("_D8demangle4testFNhG16sZv",
                       "demangle.test(__vector(short[16]))"),
        std::make_pair("_D8demangle4testFNhG2iZv",
                       "demangle.test(__vector(int[2]))"),
        std::make_pair("_D8demangle4testFNhG4iZv",
                       "demangle.test(__vector(int[4]))"),
        std::make_pair("_D8demangle4testFNhG8iZv",
                       "demangle.test(__vector(int[8]))"),
        std::make_pair("_D8demangle4testFNhG1lZv",
                       "demangle.test(__vector(long[1]))"),
        std::make_pair("_D8demangle4testFNhG2lZv",
                       "demangle.test(__vector(long[2]))"),
        std::make_pair("_D8demangle4testFNhG4lZv",
                       "demangle.test(__vector(long[4]))"),
        std::make_pair("_D8demangle4testFNhG2fZv",
                       "demangle.test(__vector(float[2]))"),
        std::make_pair("_D8demangle4testFNhG4fZv",
                       "demangle.test(__vector(float[4]))"),
        std::make_pair("_D8demangle4testFNhG8fZv",
                       "demangle.test(__vector(float[8]))"),
        std::make_pair("_D8demangle4testFNhG1dZv",
                       "demangle.test(__vector(double[1]))"),
        std::make_pair("_D8demangle4testFNhG2dZv",
                       "demangle.test(__vector(double[2]))"),
        std::make_pair("_D8demangle4testFNhG4dZv",
                       "demangle.test(__vector(double[4]))"),
        std::make_pair("_D8demangle4testFC5classZv", "demangle.test(class)"),
        std::make_pair("_D8demangle4testFC5class4testZv",
                       "demangle.test(class.test)"),
        std::make_pair("_D8demangle4testFS6structZv", "demangle.test(struct)"),
        std::make_pair("_D8demangle4testFS6struct4testZv",
                       "demangle.test(struct.test)"),
        std::make_pair("_D8demangle4testFE4enumZv", "demangle.test(enum)"),
        std::make_pair("_D8demangle4testFE4enum4testZv",
                       "demangle.test(enum.test)"),
        std::make_pair("_D8demangle4testFT7typedefZv",
                       "demangle.test(typedef)"),
        std::make_pair("_D8demangle4testFT7typedef4testZv",
                       "demangle.test(typedef.test)"),
        std::make_pair("_D8demangle4testFIaZv", "demangle.test(in char)"),
        std::make_pair("_D8demangle4testFIKaZv", "demangle.test(in ref char)"),
        std::make_pair("_D8demangle4testFJaZv", "demangle.test(out char)"),
        std::make_pair("_D8demangle4testFKaZv", "demangle.test(ref char)"),
        std::make_pair("_D8demangle4testFLaZv", "demangle.test(lazy char)"),
        std::make_pair("_D8demangle4testFMaZv", "demangle.test(scope char)"),
        std::make_pair("_D8demangle4testFNjaZv", "demangle.test(char)"),
        std::make_pair("_D8demangle4testFNkaZv", "demangle.test(return char)"),
        std::make_pair("_D8demangle4testFNlaZv", "demangle.test(char)"),
        std::make_pair("_D8demangle4testFaXv", "demangle.test(char...)"),
        std::make_pair("_D8demangle4testFaYv", "demangle.test(char, ...)"),
        std::make_pair("_D8demangle4testFaaYv",
                       "demangle.test(char, char, ...)"),
        std::make_pair("_D8demangle4testFXv", "demangle.test(...)"),
        std::make_pair("_D8demangle4testFYv", "demangle.test(, ...)"),
        std::make_pair("_D8demangle4testFaaZv", "demangle.test(char, char)"),
        std::make_pair("_D8demangle4testFB0Zv", "demangle.test(tuple())"),
        std::make_pair("_D8demangle4testFB1aZv", "demangle.test(tuple(char))"),
        std::make_pair("_D8demangle4testFB2aaZv",
                       "demangle.test(tuple(char, char))"),
        std::make_pair("_D8demangle4testFB3aaaZv",
                       "demangle.test(tuple(char, char, char))"),
        std::make_pair("_D8demangle4testFB2OaaZv",
                       "demangle.test(tuple(shared(char), char))"),
        std::make_pair("_D8demangle4testFB3aDFZaaZv",
                       "demangle.test(tuple(char, char() delegate, char))"),
        std::make_pair("_D8demangle4testFDFZaZv",
                       "demangle.test(char() delegate)"),
        std::make_pair("_D8demangle4testFDUZaZv",
                       "demangle.test(extern(C) char() delegate)"),
        std::make_pair("_D8demangle4testFDWZaZv",
                       "demangle.test(extern(Windows) char() delegate)"),
        std::make_pair("_D8demangle4testFDVZaZv",
                       "demangle.test(extern(Pascal) char() delegate)"),
        std::make_pair("_D8demangle4testFDRZaZv",
                       "demangle.test(extern(C++) char() delegate)"),
        std::make_pair("_D8demangle4testFDYZaZv",
                       "demangle.test(extern(Objective-C) char() delegate)"),
        std::make_pair("_D8demangle4testFPFZaZv",
                       "demangle.test(char() function)"),
        std::make_pair("_D8demangle4testFPUZaZv",
                       "demangle.test(extern(C) char() function)"),
        std::make_pair("_D8demangle4testFPWZaZv",
                       "demangle.test(extern(Windows) char() function)"),
        std::make_pair("_D8demangle4testFPVZaZv",
                       "demangle.test(extern(Pascal) char() function)"),
        std::make_pair("_D8demangle4testFPRZaZv",
                       "demangle.test(extern(C++) char() function)"),
        std::make_pair("_D8demangle4testFPYZaZv",
                       "demangle.test(extern(Objective-C) char() function)"),
        std::make_pair("_D8demangle4testFDFNaZaZv",
                       "demangle.test(char() pure delegate)"),
        std::make_pair("_D8demangle4testFDFNbZaZv",
                       "demangle.test(char() nothrow delegate)"),
        std::make_pair("_D8demangle4testFDFNcZaZv",
                       "demangle.test(char() ref delegate)"),
        std::make_pair("_D8demangle4testFDFNdZaZv",
                       "demangle.test(char() @property delegate)"),
        std::make_pair("_D8demangle4testFDFNeZaZv",
                       "demangle.test(char() @trusted delegate)"),
        std::make_pair("_D8demangle4testFDFNfZaZv",
                       "demangle.test(char() @safe delegate)"),
        std::make_pair("_D8demangle4testFDFNiZaZv",
                       "demangle.test(char() @nogc delegate)"),
        std::make_pair("_D8demangle4testFDFNmZaZv",
                       "demangle.test(char() @live delegate)"),
        std::make_pair("_D8demangle4testFDFNaNbZaZv",
                       "demangle.test(char() pure nothrow delegate)"),
        std::make_pair("_D8demangle4testFDFNbNaZaZv",
                       "demangle.test(char() nothrow pure delegate)"),
        std::make_pair("_D8demangle4testFDFNdNfNaZaZv",
                       "demangle.test(char() @property @safe pure delegate)"),
        std::make_pair("_D8demangle4testFNjDFZaZv",
                       "demangle.test(char() delegate)"),
        std::make_pair("_D8demangle4testFNkDFZaZv",
                       "demangle.test(return char() delegate)"),
        std::make_pair("_D8demangle4testFDFNjZaZv",
                       "demangle.test(char() return delegate)"),
        std::make_pair("_D8demangle4testFNjNkDFNjZaZv",
                       "demangle.test(return char() return delegate)"),
        std::make_pair("_D8demangle4testFNlDFZaZv",
                       "demangle.test(char() delegate)"),
        std::make_pair("_D8demangle4testFMDFZaZv",
                       "demangle.test(scope char() delegate)"),
        std::make_pair("_D8demangle4testFDFNlZaZv",
                       "demangle.test(char() scope delegate)"),
        std::make_pair("_D8demangle4testFMDFNlZaZv",
                       "demangle.test(scope char() scope delegate)"),
        std::make_pair("_D8demangle4testFNlMDFNlZaZv",
                       "demangle.test(scope char() scope delegate)"),
        std::make_pair("_D8demangle4testFPFNaZaZv",
                       "demangle.test(char() pure function)"),
        std::make_pair("_D8demangle4testFPFNbZaZv",
                       "demangle.test(char() nothrow function)"),
        std::make_pair("_D8demangle4testFPFNcZaZv",
                       "demangle.test(char() ref function)"),
        std::make_pair("_D8demangle4testFPFNdZaZv",
                       "demangle.test(char() @property function)"),
        std::make_pair("_D8demangle4testFPFNeZaZv",
                       "demangle.test(char() @trusted function)"),
        std::make_pair("_D8demangle4testFPFNfZaZv",
                       "demangle.test(char() @safe function)"),
        std::make_pair("_D8demangle4testFPFNiZaZv",
                       "demangle.test(char() @nogc function)"),
        std::make_pair("_D8demangle4testFPFNmZaZv",
                       "demangle.test(char() @live function)"),
        std::make_pair("_D8demangle4testFPFNaNbZaZv",
                       "demangle.test(char() pure nothrow function)"),
        std::make_pair("_D8demangle4testFPFNbNaZaZv",
                       "demangle.test(char() nothrow pure function)"),
        std::make_pair("_D8demangle4testFPFNdNfNaZaZv",
                       "demangle.test(char() @property @safe pure function)"),
        std::make_pair("_D8demangle4testFNjPFZaZv",
                       "demangle.test(char() function)"),
        std::make_pair("_D8demangle4testFNkPFZaZv",
                       "demangle.test(return char() function)"),
        std::make_pair("_D8demangle4testFPFNjZaZv",
                       "demangle.test(char() return function)"),
        std::make_pair("_D8demangle4testFNjNkPFNjZaZv",
                       "demangle.test(return char() return function)"),
        std::make_pair("_D8demangle4testFNlPFZaZv",
                       "demangle.test(char() function)"),
        std::make_pair("_D8demangle4testFMPFZaZv",
                       "demangle.test(scope char() function)"),
        std::make_pair("_D8demangle4testFPFNlZaZv",
                       "demangle.test(char() scope function)"),
        std::make_pair("_D8demangle4testFMPFNlZaZv",
                       "demangle.test(scope char() scope function)"),
        std::make_pair("_D8demangle4testFNlMPFNlZaZv",
                       "demangle.test(scope char() scope function)"),
        std::make_pair("_D8demangle4test6__ctorMFZv", "demangle.test.this()"),
        std::make_pair("_D8demangle4test6__dtorMFZv", "demangle.test.~this()"),
        std::make_pair("_D8demangle4test10__postblitMFZv",
                       "demangle.test.this(this)"),
        std::make_pair("_D8demangle4testFHAbaZv",
                       "demangle.test(char[bool[]])"),
        std::make_pair("_D8demangle4testFHG42caZv",
                       "demangle.test(char[creal[42]])"),
        std::make_pair("_D8demangle4testFAiXv", "demangle.test(int[]...)"),
        std::make_pair("_D8demangle4testFLAiXv",
                       "demangle.test(lazy int[]...)"),
        std::make_pair("_D8demangle4testFAiYv", "demangle.test(int[], ...)"),
        std::make_pair("_D8demangle4testFLAiYv",
                       "demangle.test(lazy int[], ...)"),
        std::make_pair("_D8demangle4testFLilZv",
                       "demangle.test(lazy int, long)"),
        std::make_pair("_D8demangle4testFLliZv",
                       "demangle.test(lazy long, int)"),
        std::make_pair(
            "_D8demangle4testFLC6ObjectLDFLiZiZi",
            "demangle.test(lazy Object, lazy int(lazy int) delegate)"),
        std::make_pair("_D8demangle4testMxFZv", "demangle.test() const"),
        std::make_pair("_D8demangle4testMyFZv", "demangle.test() immutable"),
        std::make_pair("_D8demangle4testMNgFZv", "demangle.test() inout"),
        std::make_pair("_D8demangle4testMNgxFZv",
                       "demangle.test() inout const"),
        std::make_pair("_D8demangle4testMOFZv", "demangle.test() shared"),
        std::make_pair("_D8demangle4testMOxFZv",
                       "demangle.test() shared const"),
        std::make_pair("_D8demangle4testMONgFZv",
                       "demangle.test() shared inout"),
        std::make_pair("_D8demangle4testMONgxFZv",
                       "demangle.test() shared inout const"),
        std::make_pair("_D8demangle4testFDxFZaZv",
                       "demangle.test(char() delegate const)"),
        std::make_pair("_D8demangle4testFDyFZaZv",
                       "demangle.test(char() delegate immutable)"),
        std::make_pair("_D8demangle4testFDNgFZaZv",
                       "demangle.test(char() delegate inout)"),
        std::make_pair("_D8demangle4testFDNgxFZaZv",
                       "demangle.test(char() delegate inout const)"),
        std::make_pair("_D8demangle4testFDOFZaZv",
                       "demangle.test(char() delegate shared)"),
        std::make_pair("_D8demangle4testFDOxFZaZv",
                       "demangle.test(char() delegate shared const)"),
        std::make_pair("_D8demangle4testFDONgFZaZv",
                       "demangle.test(char() delegate shared inout)"),
        std::make_pair("_D8demangle4testFDONgxFZaZv",
                       "demangle.test(char() delegate shared inout const)"),
        std::make_pair("_D8demangle004testFaZv", "demangle.test(char)"),
        std::make_pair("_D8demangle000000004testFaZv", "demangle.test(char)"),
        std::make_pair("_D8demangle9__T4testZv", "demangle.test!()"),
        std::make_pair("_D8demangle9__U4testZv", "demangle.test!()"),
        std::make_pair("_D8demangle11__T4testTaZv", "demangle.test!(char)"),
        std::make_pair("_D8demangle13__T4testTaTaZv",
                       "demangle.test!(char, char)"),
        std::make_pair("_D8demangle15__T4testTaTaTaZv",
                       "demangle.test!(char, char, char)"),
        std::make_pair("_D8demangle16__T4testTaTOiTaZv",
                       "demangle.test!(char, shared(int), char)"),
        std::make_pair("_D8demangle17__T4testS6symbolZv",
                       "demangle.test!(symbol)"),
        std::make_pair("_D8demangle23__T4testS116symbol3fooZv",
                       "demangle.test!(symbol.foo)"),
        std::make_pair("_D8demangle32__T4testS20_D6symbol3foo3barFZvZv",
                       "demangle.test!(symbol.foo.bar())"),
        std::make_pair("_D8demangle19__T4testTaS6symbolZv",
                       "demangle.test!(char, symbol)"),
        std::make_pair("_D8demangle19__T4testS6symbolTaZv",
                       "demangle.test!(symbol, char)"),
        std::make_pair("_D8demangle12__T4testHTaZv", "demangle.test!(char)"),
        std::make_pair("_D8demangle13__T4testTFZaZ6mangleFZv",
                       "demangle.test!(char() function).mangle()"),
        std::make_pair("_D8demangle15__T4testVgi123Zv", "demangle.test!(123)"),
        std::make_pair("_D8demangle15__T4testVii123Zv", "demangle.test!(123)"),
        std::make_pair("_D8demangle15__T4testVsi123Zv", "demangle.test!(123)"),
        std::make_pair("_D8demangle15__T4testVhi123Zv", "demangle.test!(123u)"),
        std::make_pair("_D8demangle15__T4testVki123Zv", "demangle.test!(123u)"),
        std::make_pair("_D8demangle15__T4testVti123Zv", "demangle.test!(123u)"),
        std::make_pair("_D8demangle15__T4testVli123Zv", "demangle.test!(123L)"),
        std::make_pair("_D8demangle15__T4testVmi123Zv",
                       "demangle.test!(123uL)"),
        std::make_pair("_D8demangle15__T4testViN123Zv", "demangle.test!(-123)"),
        std::make_pair("_D8demangle15__T4testVkN123Zv",
                       "demangle.test!(-123u)"),
        std::make_pair("_D8demangle15__T4testVlN123Zv",
                       "demangle.test!(-123L)"),
        std::make_pair("_D8demangle15__T4testVmN123Zv",
                       "demangle.test!(-123uL)"),
        std::make_pair("_D8demangle13__T4testVbi1Zv", "demangle.test!(true)"),
        std::make_pair("_D8demangle13__T4testVbi0Zv", "demangle.test!(false)"),
        std::make_pair("_D8demangle14__T4testVai10Zv",
                       "demangle.test!('\\x0a')"),
        std::make_pair("_D8demangle14__T4testVai32Zv", "demangle.test!(' ')"),
        std::make_pair("_D8demangle14__T4testVai65Zv", "demangle.test!('A')"),
        std::make_pair("_D8demangle15__T4testVai126Zv", "demangle.test!('~')"),
        std::make_pair("_D8demangle16__T4testVui1000Zv",
                       "demangle.test!('\\u03e8')"),
        std::make_pair("_D8demangle18__T4testVwi100000Zv",
                       "demangle.test!('\\U000186a0')"),
        std::make_pair("_D8demangle17__T4testVde0A8P6Zv",
                       "demangle.test!(0x0.A8p6)"),
        std::make_pair("_D8demangle16__T4testVdeA8P2Zv",
                       "demangle.test!(0xA.8p2)"),
        std::make_pair("_D8demangle18__T4testVdeN0A8P6Zv",
                       "demangle.test!(-0x0.A8p6)"),
        std::make_pair("_D8demangle31__T4testVde0F6E978D4FDF3B646P7Zv",
                       "demangle.test!(0x0.F6E978D4FDF3B646p7)"),
        std::make_pair("_D8demangle15__T4testVdeNANZv", "demangle.test!(NaN)"),
        std::make_pair("_D8demangle15__T4testVdeINFZv", "demangle.test!(Inf)"),
        std::make_pair("_D8demangle16__T4testVdeNINFZv",
                       "demangle.test!(-Inf)"),
        std::make_pair("_D8demangle23__T4testVfe0FFFFFFP128Zv",
                       "demangle.test!(0x0.FFFFFFp128)"),
        std::make_pair("_D8demangle32__T4testVde0FFFFFFFFFFFFF8P1024Zv",
                       "demangle.test!(0x0.FFFFFFFFFFFFF8p1024)"),
        std::make_pair("_D8demangle19__T4testVfe08PN125Zv",
                       "demangle.test!(0x0.8p-125)"),
        std::make_pair("_D8demangle20__T4testVde08PN1021Zv",
                       "demangle.test!(0x0.8p-1021)"),
        std::make_pair(
            "_D8demangle51__T4testVrc0C4CCCCCCCCCCCCCDP4c0B666666666666666P6Zv",
            "demangle.test!(0x0.C4CCCCCCCCCCCCCDp4+0x0.B666666666666666p6i)"),
        std::make_pair(
            "_D8demangle52__"
            "T4testVrcN0C4CCCCCCCCCCCCCDP4c0B666666666666666P6Zv",
            "demangle.test!(-0x0.C4CCCCCCCCCCCCCDp4+0x0.B666666666666666p6i)"),
        std::make_pair("_D8demangle91__"
                       "T4testVde000111222333444555666777888999AAABBBCCCDDDEEEF"
                       "FFP000111222333444555666777888999Zv",
                       "demangle.test!(0x0."
                       "00111222333444555666777888999AAABBBCCCDDDEEEFFFp0001112"
                       "22333444555666777888999)"),
        std::make_pair("_D8demangle22__T4testVG3ua3_616263Zv",
                           "demangle.test!(\"abc\")"),
        std::make_pair("_D8demangle22__T4testVG3ud3_616263Zv",
                       "demangle.test!(\"abc\"d)"),
        std::make_pair("_D8demangle22__T4testVG3uw3_616263Zv",
                       "demangle.test!(\"abc\"w)"),
        std::make_pair("_D8demangle16__T4testVAyaa0_Zv",
                       "demangle.test!(\"\")"),
        std::make_pair("_D8demangle32__T4testVAyaa8_20090a0d0c0b00ffZv",
                       "demangle.test!(\" \\t\\n\\r\\f\\v\\x00\\xff\")"),
        std::make_pair("_D8demangle22__T4testVAiA4i1i2i3i4Zv",
                       "demangle.test!([1, 2, 3, 4])"),
        std::make_pair("_D8demangle25__T4testVAdA2e08P1eN08P1Zv",
                       "demangle.test!([0x0.8p1, -0x0.8p1])"),
        std::make_pair("_D8demangle23__T4testVHiiA2i1i2i3i4Zv",
                       "demangle.test!([1:2, 3:4])"),
        std::make_pair("_D8demangle39__T4testVHAxaiA2a3_616263i1a3_646566i2Zv",
                       "demangle.test!([\"abc\":1, \"def\":2])"),
        std::make_pair("_D8demangle28__T4testVS8demangle1SS2i1i2Zv",
                       "demangle.test!(demangle.S(1, 2))"),
        std::make_pair("_D8demangle35__T4testVS8demangle1SS2i1a3_616263Zv",
                       "demangle.test!(demangle.S(1, \"abc\"))")));
